apiVersion: v1
items:
- apiVersion: security.istio.io/v1beta1
  kind: AuthorizationPolicy
  metadata:
    annotations:
      metacontroller.k8s.io/last-applied-configuration: '{"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","metadata":{"labels":{"controller-uid":"087b40d8-1cdb-4c27-93f1-240663a11120"},"name":"ml-pipeline-visualizationserver","namespace":"christensenc3526"},"spec":{"rules":[{"from":[{"source":{"principals":["cluster.local/ns/kubeflow/sa/ml-pipeline"]}}]}],"selector":{"matchLabels":{"app":"ml-pipeline-visualizationserver"}}}}'
    creationTimestamp: "2024-02-01T16:18:49Z"
    generation: 1
    labels:
      controller-uid: 087b40d8-1cdb-4c27-93f1-240663a11120
    name: ml-pipeline-visualizationserver
    namespace: christensenc3526
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Namespace
      name: christensenc3526
      uid: 087b40d8-1cdb-4c27-93f1-240663a11120
    resourceVersion: "1287486"
    uid: 225ad4f4-6e86-429b-a8bd-de0239d9588b
  spec:
    rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/kubeflow/sa/ml-pipeline
    selector:
      matchLabels:
        app: ml-pipeline-visualizationserver
- apiVersion: security.istio.io/v1beta1
  kind: AuthorizationPolicy
  metadata:
    annotations:
      role: admin
      user: christensenc3526@gmail.com
    name: ns-owner-access-istio
    namespace: christensenc3526
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: christensenc3526
      uid: 83504f57-d3c3-406d-8c6b-cd5442091687
    resourceVersion: "1287526"
    uid: 2365c954-ebef-417b-b333-6ff4a8bc826f
  spec:
    rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
          - cluster.local/ns/kubeflow/sa/ml-pipeline-ui
      when:
      - key: request.headers[x-goog-authenticated-user-email]
        values:
        - accounts.google.com:christensenc3526@gmail.com
    - when:
      - key: source.namespace
        values:
        - christensenc3526
    - to:
      - operation:
          paths:
          - /healthz
          - /metrics
          - /wait-for-drain
    - from:
      - source:
          principals:
          - cluster.local/ns/kubeflow/sa/notebook-controller-service-account
      to:
      - operation:
          methods:
          - GET
          paths:
          - '*/api/kernels'
kind: List
metadata:
  resourceVersion: ""
