apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vectorstore  
spec:
  predictor:
    containers:
    - name: kserve-container
      image: "chasechristensen/tiledb-vector-isvc:v2" #change this to your image if you are using an image you built and hosted.
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      args:
      - sanfranai #change this to your bucket if you are using a different bucket.
      env:
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            key: ACCESS_KEY
            name: minio-secret
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            key: SECRET_KEY
            name: minio-secret
      - name: CLIENT_URL
        value: "minio-service.kubeflow.svc.cluster.local:9000"
